### ISSUE TITLE
Channels in C

### ISSUE THREAD

**Issue by 6D65** [sustrik/mill#10]
Hi,

Firstly i'm sorry if it's a stupid question, i haven't programmed in C in quite a long time.
So, Mill looks interesting as a lightweight alternative to Go for concurrent software. But go has channels for communication between coroutines, and those seem like a useful thing.

I was wondering if you have seen the C implementation of channels  at (https://github.com/tylertreat/chan). And have you tried to use them together.

I was also wondering if it would be possible to make some syntactic sugar for those using the code generation lib you made. (something like c <- value). Sort of poor man's Go as a library, without the GC.

Thanks

**Comment by sustrik** [comment]
rewriting the whole thing in a completely different manner. channels are now part of the picture from the very beginning.

**Comment by 6D65** [comment]
I haven't managed to get this done, anyway. I've read the blogposts of the guy who implemented the channels in Go, and the whole thing is quite complex and requires the assistance from the Go runtime as far as I remember, the GC in Go also helps a lot. In the end I just gave up, and used Go for the project.

Good luck with your next take on this one. Looking forward to learn something new from it.
