### ISSUE TITLE
you don't have to code it from scrach, everything is done already

### ISSUE THREAD

**Issue by kostja** [sustrik/mill#13]
Hi, 

Tarantool Core is already doing what you're trying to accomplish, plus there is multi-threading support.
Just take it out (or most parts of it).

**Comment by sustrik** [comment]
Quick check seems to indicate that the project is a Lua thing, not C. Am I missing something?

**Comment by kostja** [comment]
It's built around cooperative core in C which you're trying to create.

**Comment by sustrik** [comment]
Can you point me to the code? Thanks!

**Comment by kostja** [comment]
https://github.com/tarantool/tarantool/blob/master/src/fiber.h
https://github.com/tarantool/tarantool/blob/master/src/coeio.h
https://github.com/tarantool/tarantool/blob/master/src/coio.h
https://github.com/tarantool/tarantool/blob/master/src/coio_buf.h

**Comment by sustrik** [comment]
Ah, it's based on coro. Have you found it portable enough? AFAIU it's basically impossible to have portable coroutines that work well with pthreads, however, I spoke to Russ Cox and he mentioned that THREAD(3) in p9p gets it right in almost all cases.

**Comment by kostja** [comment]
What specific problem do you have in mind? Migrating coroutines between threads?

**Comment by sustrik** [comment]
Yes. And handling of TLS in such situations.

**Comment by kostja** [comment]
We haven't implemented migration yet, we use messaging instead - fibers in different threads can exchange messages. But I mostly thought about crud like non-blocking IO in coroutines at this point, plus scheduling, even in the same thread it can be tricky, even in a single thread.
